version: '2'

services:
    nodejs:
        image: node
        container_name: node
        working_dir: /usr/app
        restart: unless-stopped
        ports:
            - "3001:3001"
        network_mode: "host"
        volumes: 
            - ./src:/usr/app
            - /home/drew/.blog_api_config:/usr/app/config
        command: bash -c 'ln -s /var/www/uploads uploads && npm install && node index.js'
