version: '2'

services:
    nodejs:
        image: node:latest
        container_name: node
        working_dir: /usr/app
        restart: unless-stopped
        network_mode: "host"
        volumes: 
            - ./src:/usr/app
            - /home/drew/.blog_api_config:/usr/app/config
            - /var/www/uploads:/usr/app/uploads
        command: bash -c 'npm install && node index.js'
