version: '3'

services:
    nodejs:
        image: node
        container_name: node
        working_dir: /usr/app
        restart: unless-stopped
        ports:
            - "3001:3001"
        network_mode: "host"
        volumes: 
            - ./src:/usr/app
        command: bash -c 'npm install && node index.js'
